language: erlang

otp_release:
    - 17.0

before_install:
    - wget https://github.com/elixir-lang/elixir/releases/download/v0.13.3/Precompiled.zip
    - unzip -d elixir Precompiled.zip
    - wget https://github.com/alco/goon/releases/download/v1.0/goon_linux_amd64.tar.gz
    - tar -xf goon_linux_amd64.tar.gz

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

script: mix test
