language: erlang

otp_release:
    - 17.1
    - 17.3

env:
    - ELIXIR_VERSION=1.0.2

before_install:
    - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
    - unzip -d elixir Precompiled.zip
    - wget https://github.com/alco/goon/releases/download/v1.1.1/goon_linux_amd64.tar.gz
    - tar -xf goon_linux_amd64.tar.gz

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

script: mix test --trace --include localbin
